project:
  type: book
  output-dir: docs
book:
  title: "Iowa State University Department of Statistics Consulting Handbook"
  author: "Jarad Niemi, Rebekah Scott"
  date: "11/4/2025"
  repo-url: https://github.com/isustatistics/consulting_handbook
  repo-branch: main
  
  chapters:
    - index.qmd
    
    - part: client_interactions.qmd
      chapters:
      - active_listening.qmd
      
    - part: statistical_methods.qmd
      chapters:
      - anova_nuances.qmd
      - exp_design.qmd
      
    - part: case_studies.qmd
      chapters:
      - example_study.qmd
      
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: show
    code-tools: true
  pdf:
    documentclass: scrreprt

editor: visual

